### ISSUE TITLE
Canonical Chord Names

### ISSUE THREAD

**Issue by yaph** [yaph/ukealong#1]
Currently different chord naming conventions are used on the site. The full list of chord names in use is at https://ukealong.com/chords/

The same chords (the same notes being played) may have different names. Only one variant should be used and existing chord names changed accordingly. Although `C#` and `Db` consist of the same pitches, these chords belong to different keys, thus the distinction makes sense.

Leave `add9` chords as they are. They are not the same as `9` chords. On the ukulele only four different notes can be played together, but they could be 1, 5, 7, 9, which is not an `add9` chord.

Below are some examples of different chord naming conventions:

* https://ukealong.com/chord/amm7/
* https://ukealong.com/chord/ammaj7/
* https://ukealong.com/chord/g7+5/
* https://ukealong.com/chord/g7add9/

Below are some examples of ambiguous names:

* https://ukealong.com/chord/asus/
* https://ukealong.com/chord/fsus/
* https://ukealong.com/chord/gsus/

## Tasks

* [x] Define rules that specify what variants to use as canonical names
* [x] Write code that changes existing chord names according to the rules and integrate it in import process
* [x] Replace ambiguous chord names

## Rules

* Use `add` instead of `+` if a note is added to the chord.
* Use `aug` instead of `+` for augmented chords.

**Comment by yaph** [comment]
Chord names are canonicalized in `clean_data.py` script.
